trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo apt update
    sudo apt install -y php php-mysql mysql-server curl
  displayName: 'Instalar PHP y MySQL'

- script: |
    sudo service mysql start

    sudo mysql -e "CREATE USER IF NOT EXISTS 'devops'@'localhost' IDENTIFIED BY 'devops123';"
    sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'devops'@'localhost' WITH GRANT OPTION;"
    sudo mysql -e "FLUSH PRIVILEGES;"
  displayName: 'Crear usuario MySQL para pruebas'

- script: |
    mysql -u devops -pdevops123 < database/database.sql
  displayName: 'Crear e importar base de datos'

- script: |
    mysql -u devops -pdevops123 -e "SHOW DATABASES;"
    mysql -u devops -pdevops123 -e "USE sistema_envios; SHOW TABLES;"
  displayName: 'Validar base de datos'

- script: |
    php -S localhost:8000 > /dev/null 2>&1 &
    sleep 5
  displayName: 'Levantar servidor PHP'

- script: |
    php test/integration/test_login.php
  displayName: 'Prueba integración - Login admin'

- script: |
    php test/integration/test_insert_envio.php
  displayName: 'Prueba integración - Insertar envío'